/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartMergeCartsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartMergeCartsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartMergeCartsResponse
        //private CartMergeCartsResponse instance;

        public CartMergeCartsResponseTests()
        {
            // TODO uncomment below to create an instance of CartMergeCartsResponse
            //instance = new CartMergeCartsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartMergeCartsResponse
        /// </summary>
        [Fact]
        public void CartMergeCartsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartMergeCartsResponse
            //Assert.IsType<CartMergeCartsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CartId'
        /// </summary>
        [Fact]
        public void CartIdTest()
        {
            // TODO unit test for the property 'CartId'
        }
    }
}
