/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartGetCartResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartGetCartResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartGetCartResponse
        //private CartGetCartResponse instance;

        public CartGetCartResponseTests()
        {
            // TODO uncomment below to create an instance of CartGetCartResponse
            //instance = new CartGetCartResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartGetCartResponse
        /// </summary>
        [Fact]
        public void CartGetCartResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartGetCartResponse
            //Assert.IsType<CartGetCartResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Cart'
        /// </summary>
        [Fact]
        public void CartTest()
        {
            // TODO unit test for the property 'Cart'
        }
    }
}
