/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartMergeCartsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartMergeCartsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartMergeCartsRequest
        //private CartMergeCartsRequest instance;

        public CartMergeCartsRequestTests()
        {
            // TODO uncomment below to create an instance of CartMergeCartsRequest
            //instance = new CartMergeCartsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartMergeCartsRequest
        /// </summary>
        [Fact]
        public void CartMergeCartsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartMergeCartsRequest
            //Assert.IsType<CartMergeCartsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'SourceCartIds'
        /// </summary>
        [Fact]
        public void SourceCartIdsTest()
        {
            // TODO unit test for the property 'SourceCartIds'
        }

        /// <summary>
        /// Test the property 'TargetCartId'
        /// </summary>
        [Fact]
        public void TargetCartIdTest()
        {
            // TODO unit test for the property 'TargetCartId'
        }
    }
}
