/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartSetCustomPriceOnItemsRequestCartItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartSetCustomPriceOnItemsRequestCartItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartSetCustomPriceOnItemsRequestCartItem
        //private CartSetCustomPriceOnItemsRequestCartItem instance;

        public CartSetCustomPriceOnItemsRequestCartItemTests()
        {
            // TODO uncomment below to create an instance of CartSetCustomPriceOnItemsRequestCartItem
            //instance = new CartSetCustomPriceOnItemsRequestCartItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartSetCustomPriceOnItemsRequestCartItem
        /// </summary>
        [Fact]
        public void CartSetCustomPriceOnItemsRequestCartItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartSetCustomPriceOnItemsRequestCartItem
            //Assert.IsType<CartSetCustomPriceOnItemsRequestCartItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'FreeOfCharge'
        /// </summary>
        [Fact]
        public void FreeOfChargeTest()
        {
            // TODO unit test for the property 'FreeOfCharge'
        }

        /// <summary>
        /// Test the property 'Unset'
        /// </summary>
        [Fact]
        public void UnsetTest()
        {
            // TODO unit test for the property 'Unset'
        }

        /// <summary>
        /// Test the property 'CustomPriceRow'
        /// </summary>
        [Fact]
        public void CustomPriceRowTest()
        {
            // TODO unit test for the property 'CustomPriceRow'
        }

        /// <summary>
        /// Test the property 'CustomPriceUnit'
        /// </summary>
        [Fact]
        public void CustomPriceUnitTest()
        {
            // TODO unit test for the property 'CustomPriceUnit'
        }

        /// <summary>
        /// Test the property 'DiscountPercentage'
        /// </summary>
        [Fact]
        public void DiscountPercentageTest()
        {
            // TODO unit test for the property 'DiscountPercentage'
        }
    }
}
