/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartSetPaymentsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartSetPaymentsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartSetPaymentsResponse
        //private CartSetPaymentsResponse instance;

        public CartSetPaymentsResponseTests()
        {
            // TODO uncomment below to create an instance of CartSetPaymentsResponse
            //instance = new CartSetPaymentsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartSetPaymentsResponse
        /// </summary>
        [Fact]
        public void CartSetPaymentsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartSetPaymentsResponse
            //Assert.IsType<CartSetPaymentsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TotalDue'
        /// </summary>
        [Fact]
        public void TotalDueTest()
        {
            // TODO unit test for the property 'TotalDue'
        }
    }
}
