/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartCartItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartCartItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartCartItem
        //private CartCartItem instance;

        public CartCartItemTests()
        {
            // TODO uncomment below to create an instance of CartCartItem
            //instance = new CartCartItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartCartItem
        /// </summary>
        [Fact]
        public void CartCartItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartCartItem
            //Assert.IsType<CartCartItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ProductGrn'
        /// </summary>
        [Fact]
        public void ProductGrnTest()
        {
            // TODO unit test for the property 'ProductGrn'
        }

        /// <summary>
        /// Test the property 'ProductConfiguration'
        /// </summary>
        [Fact]
        public void ProductConfigurationTest()
        {
            // TODO unit test for the property 'ProductConfiguration'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'ListPrice'
        /// </summary>
        [Fact]
        public void ListPriceTest()
        {
            // TODO unit test for the property 'ListPrice'
        }

        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Fact]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }

        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Fact]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }

        /// <summary>
        /// Test the property 'CustomPrice'
        /// </summary>
        [Fact]
        public void CustomPriceTest()
        {
            // TODO unit test for the property 'CustomPrice'
        }

        /// <summary>
        /// Test the property 'VatAmount'
        /// </summary>
        [Fact]
        public void VatAmountTest()
        {
            // TODO unit test for the property 'VatAmount'
        }

        /// <summary>
        /// Test the property 'VatPercentage'
        /// </summary>
        [Fact]
        public void VatPercentageTest()
        {
            // TODO unit test for the property 'VatPercentage'
        }

        /// <summary>
        /// Test the property 'VatInaccurate'
        /// </summary>
        [Fact]
        public void VatInaccurateTest()
        {
            // TODO unit test for the property 'VatInaccurate'
        }

        /// <summary>
        /// Test the property 'VatCalculated'
        /// </summary>
        [Fact]
        public void VatCalculatedTest()
        {
            // TODO unit test for the property 'VatCalculated'
        }

        /// <summary>
        /// Test the property 'LocalizedName'
        /// </summary>
        [Fact]
        public void LocalizedNameTest()
        {
            // TODO unit test for the property 'LocalizedName'
        }

        /// <summary>
        /// Test the property 'ProductCode'
        /// </summary>
        [Fact]
        public void ProductCodeTest()
        {
            // TODO unit test for the property 'ProductCode'
        }

        /// <summary>
        /// Test the property 'ProductSku'
        /// </summary>
        [Fact]
        public void ProductSkuTest()
        {
            // TODO unit test for the property 'ProductSku'
        }

        /// <summary>
        /// Test the property 'ImageGrn'
        /// </summary>
        [Fact]
        public void ImageGrnTest()
        {
            // TODO unit test for the property 'ImageGrn'
        }

        /// <summary>
        /// Test the property 'VariantOptions'
        /// </summary>
        [Fact]
        public void VariantOptionsTest()
        {
            // TODO unit test for the property 'VariantOptions'
        }

        /// <summary>
        /// Test the property 'IsVirtual'
        /// </summary>
        [Fact]
        public void IsVirtualTest()
        {
            // TODO unit test for the property 'IsVirtual'
        }

        /// <summary>
        /// Test the property 'PromotionGrns'
        /// </summary>
        [Fact]
        public void PromotionGrnsTest()
        {
            // TODO unit test for the property 'PromotionGrns'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }

        /// <summary>
        /// Test the property 'ProductData'
        /// </summary>
        [Fact]
        public void ProductDataTest()
        {
            // TODO unit test for the property 'ProductData'
        }
    }
}
