/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartShipmentData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartShipmentDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartShipmentData
        //private CartShipmentData instance;

        public CartShipmentDataTests()
        {
            // TODO uncomment below to create an instance of CartShipmentData
            //instance = new CartShipmentData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartShipmentData
        /// </summary>
        [Fact]
        public void CartShipmentDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartShipmentData
            //Assert.IsType<CartShipmentData>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'ShipmentGrn'
        /// </summary>
        [Fact]
        public void ShipmentGrnTest()
        {
            // TODO unit test for the property 'ShipmentGrn'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'CartItemIds'
        /// </summary>
        [Fact]
        public void CartItemIdsTest()
        {
            // TODO unit test for the property 'CartItemIds'
        }

        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'VatAmount'
        /// </summary>
        [Fact]
        public void VatAmountTest()
        {
            // TODO unit test for the property 'VatAmount'
        }

        /// <summary>
        /// Test the property 'VatPercentage'
        /// </summary>
        [Fact]
        public void VatPercentageTest()
        {
            // TODO unit test for the property 'VatPercentage'
        }

        /// <summary>
        /// Test the property 'VatInaccurate'
        /// </summary>
        [Fact]
        public void VatInaccurateTest()
        {
            // TODO unit test for the property 'VatInaccurate'
        }

        /// <summary>
        /// Test the property 'VatCalculated'
        /// </summary>
        [Fact]
        public void VatCalculatedTest()
        {
            // TODO unit test for the property 'VatCalculated'
        }
    }
}
