/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartAddProductsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartAddProductsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartAddProductsResponse
        //private CartAddProductsResponse instance;

        public CartAddProductsResponseTests()
        {
            // TODO uncomment below to create an instance of CartAddProductsResponse
            //instance = new CartAddProductsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartAddProductsResponse
        /// </summary>
        [Fact]
        public void CartAddProductsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartAddProductsResponse
            //Assert.IsType<CartAddProductsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
