/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartAddProductsRequestItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartAddProductsRequestItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartAddProductsRequestItem
        //private CartAddProductsRequestItem instance;

        public CartAddProductsRequestItemTests()
        {
            // TODO uncomment below to create an instance of CartAddProductsRequestItem
            //instance = new CartAddProductsRequestItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartAddProductsRequestItem
        /// </summary>
        [Fact]
        public void CartAddProductsRequestItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartAddProductsRequestItem
            //Assert.IsType<CartAddProductsRequestItem>(instance);
        }

        /// <summary>
        /// Test the property 'ProductGrn'
        /// </summary>
        [Fact]
        public void ProductGrnTest()
        {
            // TODO unit test for the property 'ProductGrn'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'ConfigurationSelections'
        /// </summary>
        [Fact]
        public void ConfigurationSelectionsTest()
        {
            // TODO unit test for the property 'ConfigurationSelections'
        }
    }
}
