/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartItemCustomPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartItemCustomPriceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartItemCustomPrice
        //private CartItemCustomPrice instance;

        public CartItemCustomPriceTests()
        {
            // TODO uncomment below to create an instance of CartItemCustomPrice
            //instance = new CartItemCustomPrice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartItemCustomPrice
        /// </summary>
        [Fact]
        public void CartItemCustomPriceInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartItemCustomPrice
            //Assert.IsType<CartItemCustomPrice>(instance);
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'PreviousPrice'
        /// </summary>
        [Fact]
        public void PreviousPriceTest()
        {
            // TODO unit test for the property 'PreviousPrice'
        }
    }
}
