/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartListCartsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartListCartsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartListCartsResponse
        //private CartListCartsResponse instance;

        public CartListCartsResponseTests()
        {
            // TODO uncomment below to create an instance of CartListCartsResponse
            //instance = new CartListCartsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartListCartsResponse
        /// </summary>
        [Fact]
        public void CartListCartsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartListCartsResponse
            //Assert.IsType<CartListCartsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Carts'
        /// </summary>
        [Fact]
        public void CartsTest()
        {
            // TODO unit test for the property 'Carts'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
