/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartUpdateCartRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartUpdateCartRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartUpdateCartRequest
        //private CartUpdateCartRequest instance;

        public CartUpdateCartRequestTests()
        {
            // TODO uncomment below to create an instance of CartUpdateCartRequest
            //instance = new CartUpdateCartRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartUpdateCartRequest
        /// </summary>
        [Fact]
        public void CartUpdateCartRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartUpdateCartRequest
            //Assert.IsType<CartUpdateCartRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'CartId'
        /// </summary>
        [Fact]
        public void CartIdTest()
        {
            // TODO unit test for the property 'CartId'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'PayloadMask'
        /// </summary>
        [Fact]
        public void PayloadMaskTest()
        {
            // TODO unit test for the property 'PayloadMask'
        }
    }
}
