/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartProductConfigurationStepOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartProductConfigurationStepOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartProductConfigurationStepOption
        //private CartProductConfigurationStepOption instance;

        public CartProductConfigurationStepOptionTests()
        {
            // TODO uncomment below to create an instance of CartProductConfigurationStepOption
            //instance = new CartProductConfigurationStepOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartProductConfigurationStepOption
        /// </summary>
        [Fact]
        public void CartProductConfigurationStepOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartProductConfigurationStepOption
            //Assert.IsType<CartProductConfigurationStepOption>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'PriceVariation'
        /// </summary>
        [Fact]
        public void PriceVariationTest()
        {
            // TODO unit test for the property 'PriceVariation'
        }

        /// <summary>
        /// Test the property 'WeightVariation'
        /// </summary>
        [Fact]
        public void WeightVariationTest()
        {
            // TODO unit test for the property 'WeightVariation'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'HasQuantity'
        /// </summary>
        [Fact]
        public void HasQuantityTest()
        {
            // TODO unit test for the property 'HasQuantity'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
    }
}
