/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartPostalAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartPostalAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartPostalAddress
        //private CartPostalAddress instance;

        public CartPostalAddressTests()
        {
            // TODO uncomment below to create an instance of CartPostalAddress
            //instance = new CartPostalAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartPostalAddress
        /// </summary>
        [Fact]
        public void CartPostalAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartPostalAddress
            //Assert.IsType<CartPostalAddress>(instance);
        }

        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Fact]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }

        /// <summary>
        /// Test the property 'RegionCode'
        /// </summary>
        [Fact]
        public void RegionCodeTest()
        {
            // TODO unit test for the property 'RegionCode'
        }

        /// <summary>
        /// Test the property 'LanguageCode'
        /// </summary>
        [Fact]
        public void LanguageCodeTest()
        {
            // TODO unit test for the property 'LanguageCode'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'SortingCode'
        /// </summary>
        [Fact]
        public void SortingCodeTest()
        {
            // TODO unit test for the property 'SortingCode'
        }

        /// <summary>
        /// Test the property 'AdministrativeArea'
        /// </summary>
        [Fact]
        public void AdministrativeAreaTest()
        {
            // TODO unit test for the property 'AdministrativeArea'
        }

        /// <summary>
        /// Test the property 'Locality'
        /// </summary>
        [Fact]
        public void LocalityTest()
        {
            // TODO unit test for the property 'Locality'
        }

        /// <summary>
        /// Test the property 'Sublocality'
        /// </summary>
        [Fact]
        public void SublocalityTest()
        {
            // TODO unit test for the property 'Sublocality'
        }

        /// <summary>
        /// Test the property 'AddressLines'
        /// </summary>
        [Fact]
        public void AddressLinesTest()
        {
            // TODO unit test for the property 'AddressLines'
        }

        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [Fact]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }

        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Fact]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
    }
}
