/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartProductConfigurationSelectionOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartProductConfigurationSelectionOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartProductConfigurationSelectionOption
        //private CartProductConfigurationSelectionOption instance;

        public CartProductConfigurationSelectionOptionTests()
        {
            // TODO uncomment below to create an instance of CartProductConfigurationSelectionOption
            //instance = new CartProductConfigurationSelectionOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartProductConfigurationSelectionOption
        /// </summary>
        [Fact]
        public void CartProductConfigurationSelectionOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartProductConfigurationSelectionOption
            //Assert.IsType<CartProductConfigurationSelectionOption>(instance);
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
    }
}
