/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartMoney
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartMoneyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartMoney
        //private CartMoney instance;

        public CartMoneyTests()
        {
            // TODO uncomment below to create an instance of CartMoney
            //instance = new CartMoney();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartMoney
        /// </summary>
        [Fact]
        public void CartMoneyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartMoney
            //Assert.IsType<CartMoney>(instance);
        }

        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

        /// <summary>
        /// Test the property 'Micros'
        /// </summary>
        [Fact]
        public void MicrosTest()
        {
            // TODO unit test for the property 'Micros'
        }
    }
}
