/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartUpdateProductsRequestItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartUpdateProductsRequestItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartUpdateProductsRequestItem
        //private CartUpdateProductsRequestItem instance;

        public CartUpdateProductsRequestItemTests()
        {
            // TODO uncomment below to create an instance of CartUpdateProductsRequestItem
            //instance = new CartUpdateProductsRequestItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartUpdateProductsRequestItem
        /// </summary>
        [Fact]
        public void CartUpdateProductsRequestItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartUpdateProductsRequestItem
            //Assert.IsType<CartUpdateProductsRequestItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'ConfigurationSelections'
        /// </summary>
        [Fact]
        public void ConfigurationSelectionsTest()
        {
            // TODO unit test for the property 'ConfigurationSelections'
        }
    }
}
