/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing CartCreateCartResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartCreateCartResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartCreateCartResponse
        //private CartCreateCartResponse instance;

        public CartCreateCartResponseTests()
        {
            // TODO uncomment below to create an instance of CartCreateCartResponse
            //instance = new CartCreateCartResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartCreateCartResponse
        /// </summary>
        [Fact]
        public void CartCreateCartResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartCreateCartResponse
            //Assert.IsType<CartCreateCartResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
