/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing ListCartsRequestFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCartsRequestFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCartsRequestFilter
        //private ListCartsRequestFilter instance;

        public ListCartsRequestFilterTests()
        {
            // TODO uncomment below to create an instance of ListCartsRequestFilter
            //instance = new ListCartsRequestFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCartsRequestFilter
        /// </summary>
        [Fact]
        public void ListCartsRequestFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCartsRequestFilter
            //Assert.IsType<ListCartsRequestFilter>(instance);
        }

        /// <summary>
        /// Test the property 'SearchTerms'
        /// </summary>
        [Fact]
        public void SearchTermsTest()
        {
            // TODO unit test for the property 'SearchTerms'
        }

        /// <summary>
        /// Test the property 'CustomerEmails'
        /// </summary>
        [Fact]
        public void CustomerEmailsTest()
        {
            // TODO unit test for the property 'CustomerEmails'
        }

        /// <summary>
        /// Test the property 'CustomerFirstnames'
        /// </summary>
        [Fact]
        public void CustomerFirstnamesTest()
        {
            // TODO unit test for the property 'CustomerFirstnames'
        }

        /// <summary>
        /// Test the property 'CustomerLastnames'
        /// </summary>
        [Fact]
        public void CustomerLastnamesTest()
        {
            // TODO unit test for the property 'CustomerLastnames'
        }

        /// <summary>
        /// Test the property 'CustomerPhones'
        /// </summary>
        [Fact]
        public void CustomerPhonesTest()
        {
            // TODO unit test for the property 'CustomerPhones'
        }

        /// <summary>
        /// Test the property 'CartIds'
        /// </summary>
        [Fact]
        public void CartIdsTest()
        {
            // TODO unit test for the property 'CartIds'
        }

        /// <summary>
        /// Test the property 'CartStatus'
        /// </summary>
        [Fact]
        public void CartStatusTest()
        {
            // TODO unit test for the property 'CartStatus'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'AgentGrn'
        /// </summary>
        [Fact]
        public void AgentGrnTest()
        {
            // TODO unit test for the property 'AgentGrn'
        }
    }
}
