/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing ListCartsRequestFilterCartStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCartsRequestFilterCartStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCartsRequestFilterCartStatus
        //private ListCartsRequestFilterCartStatus instance;

        public ListCartsRequestFilterCartStatusTests()
        {
            // TODO uncomment below to create an instance of ListCartsRequestFilterCartStatus
            //instance = new ListCartsRequestFilterCartStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCartsRequestFilterCartStatus
        /// </summary>
        [Fact]
        public void ListCartsRequestFilterCartStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCartsRequestFilterCartStatus
            //Assert.IsType<ListCartsRequestFilterCartStatus>(instance);
        }
    }
}
