/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing ListCartsRequestSort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCartsRequestSortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCartsRequestSort
        //private ListCartsRequestSort instance;

        public ListCartsRequestSortTests()
        {
            // TODO uncomment below to create an instance of ListCartsRequestSort
            //instance = new ListCartsRequestSort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCartsRequestSort
        /// </summary>
        [Fact]
        public void ListCartsRequestSortInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCartsRequestSort
            //Assert.IsType<ListCartsRequestSort>(instance);
        }

        /// <summary>
        /// Test the property 'EvaluationOrder'
        /// </summary>
        [Fact]
        public void EvaluationOrderTest()
        {
            // TODO unit test for the property 'EvaluationOrder'
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
