/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing ListCartsRequestFilterDate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCartsRequestFilterDateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCartsRequestFilterDate
        //private ListCartsRequestFilterDate instance;

        public ListCartsRequestFilterDateTests()
        {
            // TODO uncomment below to create an instance of ListCartsRequestFilterDate
            //instance = new ListCartsRequestFilterDate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCartsRequestFilterDate
        /// </summary>
        [Fact]
        public void ListCartsRequestFilterDateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCartsRequestFilterDate
            //Assert.IsType<ListCartsRequestFilterDate>(instance);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
    }
}
