/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cart.Model;
using cart.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cart.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateCartRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCartRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCartRequestPayload
        //private UpdateCartRequestPayload instance;

        public UpdateCartRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of UpdateCartRequestPayload
            //instance = new UpdateCartRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCartRequestPayload
        /// </summary>
        [Fact]
        public void UpdateCartRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateCartRequestPayload
            //Assert.IsType<UpdateCartRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'CartStatus'
        /// </summary>
        [Fact]
        public void CartStatusTest()
        {
            // TODO unit test for the property 'CartStatus'
        }

        /// <summary>
        /// Test the property 'CustomerData'
        /// </summary>
        [Fact]
        public void CustomerDataTest()
        {
            // TODO unit test for the property 'CustomerData'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
    }
}
