/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cart.Client.OpenAPIDateConverter;

namespace cart.Model
{
    /// <summary>
    /// CartProductConfigurationSelection
    /// </summary>
    [DataContract(Name = "cartProductConfigurationSelection")]
    public partial class CartProductConfigurationSelection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartProductConfigurationSelection" /> class.
        /// </summary>
        /// <param name="stepGrn">stepGrn.</param>
        /// <param name="options">options.</param>
        public CartProductConfigurationSelection(string stepGrn = default(string), List<CartProductConfigurationSelectionOption> options = default(List<CartProductConfigurationSelectionOption>))
        {
            this.StepGrn = stepGrn;
            this.Options = options;
        }

        /// <summary>
        /// Gets or Sets StepGrn
        /// </summary>
        [DataMember(Name = "stepGrn", EmitDefaultValue = false)]
        public string StepGrn { get; set; }

        /// <summary>
        /// Gets or Sets Options
        /// </summary>
        [DataMember(Name = "options", EmitDefaultValue = false)]
        public List<CartProductConfigurationSelectionOption> Options { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CartProductConfigurationSelection {\n");
            sb.Append("  StepGrn: ").Append(StepGrn).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
