/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cart.Client.OpenAPIDateConverter;

namespace cart.Model
{
    /// <summary>
    /// CartMergeCartsRequest
    /// </summary>
    [DataContract(Name = "cartMergeCartsRequest")]
    public partial class CartMergeCartsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartMergeCartsRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId.</param>
        /// <param name="sourceCartIds">sourceCartIds.</param>
        /// <param name="targetCartId">targetCartId.</param>
        public CartMergeCartsRequest(string tenantId = default(string), List<string> sourceCartIds = default(List<string>), string targetCartId = default(string))
        {
            this.TenantId = tenantId;
            this.SourceCartIds = sourceCartIds;
            this.TargetCartId = targetCartId;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", EmitDefaultValue = false)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets SourceCartIds
        /// </summary>
        [DataMember(Name = "sourceCartIds", EmitDefaultValue = false)]
        public List<string> SourceCartIds { get; set; }

        /// <summary>
        /// Gets or Sets TargetCartId
        /// </summary>
        [DataMember(Name = "targetCartId", EmitDefaultValue = false)]
        public string TargetCartId { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CartMergeCartsRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  SourceCartIds: ").Append(SourceCartIds).Append("\n");
            sb.Append("  TargetCartId: ").Append(TargetCartId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
