/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cart.Client.OpenAPIDateConverter;

namespace cart.Model
{
    /// <summary>
    /// CartUpdateProductsRequestItem
    /// </summary>
    [DataContract(Name = "cartUpdateProductsRequestItem")]
    public partial class CartUpdateProductsRequestItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartUpdateProductsRequestItem" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="configurationSelections">configurationSelections.</param>
        public CartUpdateProductsRequestItem(string id = default(string), long quantity = default(long), List<CartProductConfigurationSelection> configurationSelections = default(List<CartProductConfigurationSelection>))
        {
            this.Id = id;
            this.Quantity = quantity;
            this.ConfigurationSelections = configurationSelections;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public long Quantity { get; set; }

        /// <summary>
        /// Gets or Sets ConfigurationSelections
        /// </summary>
        [DataMember(Name = "configurationSelections", EmitDefaultValue = false)]
        public List<CartProductConfigurationSelection> ConfigurationSelections { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CartUpdateProductsRequestItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  ConfigurationSelections: ").Append(ConfigurationSelections).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
