/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cart.Client.OpenAPIDateConverter;

namespace cart.Model
{
    /// <summary>
    /// UpdateCartRequestPayload
    /// </summary>
    [DataContract(Name = "UpdateCartRequestPayload")]
    public partial class UpdateCartRequestPayload : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets CartStatus
        /// </summary>
        [DataMember(Name = "cartStatus", EmitDefaultValue = false)]
        public CartCartStatus? CartStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCartRequestPayload" /> class.
        /// </summary>
        /// <param name="cartStatus">cartStatus.</param>
        /// <param name="customerData">customerData.</param>
        /// <param name="locale">locale.</param>
        public UpdateCartRequestPayload(CartCartStatus? cartStatus = default(CartCartStatus?), CartCustomerData customerData = default(CartCustomerData), string locale = default(string))
        {
            this.CartStatus = cartStatus;
            this.CustomerData = customerData;
            this.Locale = locale;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets CustomerData
        /// </summary>
        [DataMember(Name = "customerData", EmitDefaultValue = false)]
        public CartCustomerData CustomerData { get; set; }

        /// <summary>
        /// Gets or Sets Locale
        /// </summary>
        [DataMember(Name = "locale", EmitDefaultValue = false)]
        public string Locale { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCartRequestPayload {\n");
            sb.Append("  CartStatus: ").Append(CartStatus).Append("\n");
            sb.Append("  CustomerData: ").Append(CustomerData).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
