/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using cart.Client;
using cart.Api;
// uncomment below to import models
//using cart.Model;

namespace cart.Test.Api
{
    /// <summary>
    ///  Class for testing AddressesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AddressesApiTests : IDisposable
    {
        private AddressesApi instance;

        public AddressesApiTests()
        {
            instance = new AddressesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AddressesApi
            //Assert.IsType<AddressesApi>(instance);
        }

        /// <summary>
        /// Test SetBillingAddress
        /// </summary>
        [Fact]
        public void SetBillingAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartSetBillingAddressRequest body = null;
            //var response = instance.SetBillingAddress(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test SetShipmentAddress
        /// </summary>
        [Fact]
        public void SetShipmentAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartSetShipmentAddressRequest body = null;
            //var response = instance.SetShipmentAddress(body);
            //Assert.IsType<Object>(response);
        }
    }
}
