/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using cart.Client;
using cart.Api;
// uncomment below to import models
//using cart.Model;

namespace cart.Test.Api
{
    /// <summary>
    ///  Class for testing PaymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PaymentsApiTests : IDisposable
    {
        private PaymentsApi instance;

        public PaymentsApiTests()
        {
            instance = new PaymentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PaymentsApi
            //Assert.IsType<PaymentsApi>(instance);
        }

        /// <summary>
        /// Test ListPaymentMethods
        /// </summary>
        [Fact]
        public void ListPaymentMethodsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartListPaymentMethodsRequest body = null;
            //var response = instance.ListPaymentMethods(body);
            //Assert.IsType<CartListPaymentMethodsResponse>(response);
        }

        /// <summary>
        /// Test SetSetPayments
        /// </summary>
        [Fact]
        public void SetSetPaymentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartSetPaymentsRequest body = null;
            //var response = instance.SetSetPayments(body);
            //Assert.IsType<CartSetPaymentsResponse>(response);
        }
    }
}
