/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using cart.Client;
using cart.Api;
// uncomment below to import models
//using cart.Model;

namespace cart.Test.Api
{
    /// <summary>
    ///  Class for testing PromotionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PromotionsApiTests : IDisposable
    {
        private PromotionsApi instance;

        public PromotionsApiTests()
        {
            instance = new PromotionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PromotionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PromotionsApi
            //Assert.IsType<PromotionsApi>(instance);
        }

        /// <summary>
        /// Test ApplyCoupons
        /// </summary>
        [Fact]
        public void ApplyCouponsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartApplyCouponsRequest body = null;
            //var response = instance.ApplyCoupons(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test RemoveCoupons
        /// </summary>
        [Fact]
        public void RemoveCouponsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartRemoveCouponsRequest body = null;
            //var response = instance.RemoveCoupons(body);
            //Assert.IsType<Object>(response);
        }
    }
}
