/*
 * Cart Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using cart.Client;
using cart.Api;
// uncomment below to import models
//using cart.Model;

namespace cart.Test.Api
{
    /// <summary>
    ///  Class for testing ShipmentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ShipmentsApiTests : IDisposable
    {
        private ShipmentsApi instance;

        public ShipmentsApiTests()
        {
            instance = new ShipmentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipmentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ShipmentsApi
            //Assert.IsType<ShipmentsApi>(instance);
        }

        /// <summary>
        /// Test ListShipmentMethods
        /// </summary>
        [Fact]
        public void ListShipmentMethodsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartListShipmentMethodsRequest body = null;
            //var response = instance.ListShipmentMethods(body);
            //Assert.IsType<CartListShipmentMethodsResponse>(response);
        }

        /// <summary>
        /// Test SetShipments
        /// </summary>
        [Fact]
        public void SetShipmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CartSetShipmentsRequest body = null;
            //var response = instance.SetShipments(body);
            //Assert.IsType<Object>(response);
        }
    }
}
